Bookers/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'books#top'

  get 'new' => 'books#new'
  get 'top' => 'books#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'

end

Bookers/app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true
end

Bookers/app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top

  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id), notice: 'Book was successfully created.'
    else
      render action: 'index'
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path(@book.id), notice: 'Book was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @books = Book.all
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_path, notice: 'Book was successfully destroyed.'
    else
      render action: 'index'
    end
  end

  private

  def book_params
      params.require(:book).permit(:title, :body)
  end

end

Bookers/app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book, url:"/books/#{@book.id}") do |f| %>

    <% if @book.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <div class="field">
        <%= f.label :title, :class => 'book_title' %>
        <%= f.text_field :title, :class => 'book_title' %>
    </div>
    <div class="field">
        <%= f.label :body, :class => 'book_body' %>
        <%= f.text_area :body, :class => 'book_body' %>
    </div>
    <div class="actions">
        <%= f.submit 'Update Book' %>
    </div>
    <%= link_to "Show", book_path(@book.id), :class => "show_#{@book.id}" %> | <%= link_to "Back", books_path, :class => "back" %>
<% end %>

Bookers/app/views/books/index.html.erb
<% if flash[:notice] %>
    <p id='notice'><%= flash[:notice] %></p>
<% end %>

<h1>Books</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id), :class => "show_#{book.id}" %></td>
        <td><%= link_to "Edit", edit_book_path(book.id), :class => "edit_#{book.id}"  %></td>
        <td><%= link_to "Destroy", destroy_book_path(book.id), method: :delete, "data-confirm" => "Are You Sure?", :class => "destroy_#{book.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2>New book</h2>
<!-- form_for部分 -->
<%= form_for(@book, url: '/books') do |f| %>

    <% if @book.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this article from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    <div class="field">
        <%= f.label :title, :class => 'book_title' %>
        <%= f.text_field :title, :class => 'book_title' %>
    </div>
    <div class="field">
        <%= f.label :body, :class => 'book_body' %>
        <%= f.text_area :body, :class => 'book_body' %>
    </div>
    <div class="actions">
        <%= f.submit 'Create Book' %>
    </div>

<% end %>

Bookers/app/views/books/show.html.erb
<% if flash[:notice] %>
    <p id='notice'><%= flash[:notice] %></p>
<% end %>

<p><b>Title: </b><%= @book.title %></p>
<p><b>Body: </b><%= @book.body %></p>

<%= link_to "Edit", edit_book_path(@book.id), :class => "edit_#{@book.id}" %> | <%= link_to "Back", books_path, :class => "back" %>

<%#
<%= link_to "Edit", edit_book_path(@book.id) %
<%= link_to "Destroy", destroy_book_path(@book.id), method: :delete, "data-confirm" => "Are You Sure?" %
%>

Bookers/app/views/books/top.html.erb
<h1>ようこそ Bookers へ !</h1>
<p><strong>Bookers</strong> では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<p><%= link_to "start", books_path %></p>

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>